#!/usr/bin/env python
import os
from git import Repo
from wordcloud import WordCloud
import argparse


parser = argparse.ArgumentParser(description='wordcloud from git history.')
parser.add_argument('-o', '--output-filename', help='Where to write file')
# parser.add_argument('-a', '--authors', nargs='0', help='Cloud of authors')
# parser.add_argument('-m', '--messages', help='Cloud of commit messages')

args = parser.parse_args()
# parser.print_help()


working_dir = os.getcwd()
repo = Repo(working_dir)
assert not repo.bare

messages = ''
authors = ''
for l in repo.iter_commits():

  name = l.author.name.replace(' ', '')
  authors += str(name) +' '

  messages += l.message
  #print l.message



wordcloud = WordCloud().generate(messages)
#wordcloud = WordCloud().generate(authors)
wordcloud.to_file(args.output_filename)

print "File written to {filename}".format(filename=args.output_filename)

